### PR TITLE
Unify favicons across the site

### PR DESCRIPTION
**Pull request by alexmarple**
This PR deletes the Zanzibar-specific favicon in favor of the Authzed favicon for cross-site unification.

### CODE REVIEW

**Review by samkim — COMMENTED** [review]
Mind reverting the quote changes?

**Comment by alexmarple** [comment]
@samkim which quote changes?

**Comment by alexmarple** [comment]
Oooooh. My computer swapped single for double quotes. Gotcha.

**Review by samkim — APPROVED** [review]
LGTM

**Pull request merged**
